---
- hosts: NewHomepage
  tasks:
  - name: “Copy Files”
    copy:
       dest: /var/www/html/
       src: index.html
    notify: “web_restart”
  - name: “Starting Web Server”
    service:
       name: httpd
       state: started
  handlers:
  — name: “web_restart”
    service:
       name: httpd
       state: restarted
