---
- hosts: NewHomepage
  tasks:
  - name: “Copy Files”
    copy:
       dest: /var/www/html/
       src: index.html
    notify: “web_restart”
  - name: “Starting Web Server”
    service:
       name: httpd
       state: started
  - name: Create firewall rule for apache service
    firewalld:
      service: http
      zone: FedoraWorkstation
      permanent: yes
      immediate: yes
      state: enabled
  handlers:
  - name: “web_restart”
    service:
       name: httpd
       state: restarted
