---
- name: install and start apache
  hosts: WebServers
  become: yes

  tasks:
  - name: Apache latest version installation
    dnf:
      name: httpd
      state: latest
  - name: Enable service to start on boot up
    service:
      name: httpd
      state: started
  - name: Create firewall rule for apache service
    firewalld:
      service: http
      zone: public
      port: 80/tcp
      permanent: yes
      immediate: yes
      state: enabled
  - name: Create firewall rule for apache service
    firewalld:
      service: https
      zone: public
      permanent: yes
      immediate: yes
      state: enabled
  handlers:
  - name: Restart apache service
    service:
      name: httpd
      state: restarted
