---
- name: Network Device management
  hosts: NetworkDevices
  gather_facts: false

  tasks:
  - name: Remove a class from QOS
    ansible.builtin.raw: ./kerbynet.cgi/scripts/qos_deleteclass VPN99 ANSIBLE001
