---
- name: Remote File copy
  hosts: Cloud
  gather_facts: false
  tasks:
    - name: copy a file remotely
      win_get_url:
        url: https://github.com/PhillipMSchwartz/AnsiblePlaybooks/blob/main/Fun.png
        dest: C:\ansible_examples
        
