---
- name: change windows environment variable
  hosts: Cloud
  tasks:
   - name: Set an environment variable for all users
     win_environment:
       state: present
       name: Hi_Ansible_Fans
       value: Pretty cool
       level: machine
